from enum import Enum as discriptors
class __NULLABLES__(discriptors):
    __NULLABLES__ = ['NULLABLE', 'NOT NULLABLE']
    EMPTY_STATE = ""


Criticals = {
    "__TRACE__": {
        "value": "TRACE",
    },
    "__DEBUG__": {
        "value": "DEBUG",
    },
    "__INFO__": {
        "value": "INFO",
    },
    "__WARNING__": {
        "value": "WARNING",
    },
    "__ERROR__": {
        "value": "ERROR",
    },
    "__CRITICAL__": {
        "value": "CRITICAL",
    },
    "__ALERT__": {
        "value": "ALERT",
    },
    "__EMERGENCY__": {
        "value": "EMERGENCY",
    }
}



class Role(discriptors):
    SUPER_ADMIN = "SUPER_ADMIN"
    AGENCY_OWNER = "AGENCY_OWNER"
    AGENCY_ADMIN = "AGENCY_ADMIN"
    SUBACCOUNT_USER = "SUBACCOUNT_USER"
    SUBACCOUNT_GUEST = "SUBACCOUNT_GUEST"
    CUSTOMER = "CUSTOMER"
    SUPPORT = "SUPPORT"
    AUDITOR = "AUDITOR"
    TEAM_LEAD = "TEAM_LEAD"
    PRODUCT_MANAGER = "PRODUCT_MANAGER"
    SALES_REPRESENTATIVE = "SALES_REPRESENTATIVE"
    DEVELOPER = "DEVELOPER"
    MARKETING_SPECIALIST = "MARKETING_SPECIALIST"
    DATA_ANALYST = "DATA_ANALYST"
    HR_MANAGER = "HR_MANAGER"
    FINANCE_MANAGER = "FINANCE_MANAGER"
    LEGAL = "LEGAL"
    ADMINISTRATOR = "ADMINISTRATOR"
    CONTENT_MANAGER = "CONTENT_MANAGER"
    INTEGRATION_MANAGER = "INTEGRATION_MANAGER"
    CUSTOMER_SUPPORT = "CUSTOMER_SUPPORT"
    INTERNAL_AUDITOR = "INTERNAL_AUDITOR"
    PRODUCT_OWNER = "PRODUCT_OWNER"
    SALES_MANAGER = "SALES_MANAGER"
    OPERATIONS_MANAGER = "OPERATIONS_MANAGER"
    ACCOUNTANT = "ACCOUNTANT"
    IT_MANAGER = "IT_MANAGER"
    MARKETING_DIRECTOR = "MARKETING_DIRECTOR"
    BUSINESS_ANALYST = "BUSINESS_ANALYST"
    CUSTOMER_RELATIONS_MANAGER = "CUSTOMER_RELATIONS_MANAGER"
    PROCUREMENT_MANAGER = "PROCUREMENT_MANAGER"
    SECURITY_ADMIN = "SECURITY_ADMIN"
    DATA_SCIENTIST = "DATA_SCIENTIST"
    SYSTEM_ADMIN = "SYSTEM_ADMIN"
    UX_UI_DESIGNER = "UX_UI_DESIGNER"
    BUSINESS_DEVELOPER = "BUSINESS_DEVELOPER"
    SOCIAL_MEDIA_MANAGER = "SOCIAL_MEDIA_MANAGER"
    COMPLIANCE_OFFICER = "COMPLIANCE_OFFICER"
    QUALITY_ASSURANCE = "QUALITY_ASSURANCE"
    DEVOPS_ENGINEER = "DEVOPS_ENGINEER"
    SYSTEM_ARCHITECT = "SYSTEM_ARCHITECT"
    CUSTOMER_SUCCESS_MANAGER = "CUSTOMER_SUCCESS_MANAGER"
    SOFTWARE_ENGINEER = "SOFTWARE_ENGINEER"

class InvitationStatus(discriptors):
    ACCEPTED = "ACCEPTED"
    REVOKED = "REVOKED"
    PENDING = "PENDING"
    EXPIRED = "EXPIRED"
    DECLINED = "DECLINED"
    REISSUED = "REISSUED"
    SUSPENDED = "SUSPENDED"
    INACTIVE = "INACTIVE"
    COMPLETED = "COMPLETED"
    INVALID = "INVALID"

class ProjectStatus(discriptors):
    ACTIVE = "Active"
    COMPLETED = "Completed"
    ON_HOLD = "On Hold"
    CANCELLED = "Cancelled"

class AccountStatus(discriptors):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    LOCKED = "LOCKED"
    DELETED = "DELETED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    ARCHIVED = "ARCHIVED"
    DISABLED = "DISABLED"
    INACTIVE = "INACTIVE"
    UNVERIFIED = "UNVERIFIED"
    TEMPORARY = "TEMPORARY"

class AuthProvider(discriptors):
    LOCAL = "LOCAL"
    GOOGLE = "GOOGLE"
    FACEBOOK = "FACEBOOK"
    TWITTER = "TWITTER"
    GITHUB = "GITHUB"
    APPLE = "APPLE"
    LINKEDIN = "LINKEDIN"
    MICROSOFT = "MICROSOFT"
    AMAZON = "AMAZON"
    SLACK = "SLACK"
    INSTAGRAM = "INSTAGRAM"
    ZOOM = "ZOOM"

class NotificationType(discriptors):
    EMAIL = "EMAIL"
    SMS = "SMS"
    PUSH = "PUSH"
    IN_APP = "IN_APP"
    WEBHOOK = "WEBHOOK"
    WHATSAPP = "WHATSAPP"
    TELEGRAM = "TELEGRAM"
    SLACK = "SLACK"
    BROWSER = "BROWSER"
    DESKTOP_ALERT = "DESKTOP_ALERT"
    NEWSLETTER = "NEWSLETTER"

class AuditAction(discriptors):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    EXPORT = "EXPORT"
    IMPORT = "IMPORT"
    ACCESS_DENIED = "ACCESS_DENIED"
    PASSWORD_RESET = "PASSWORD_RESET"
    CONFIGURATION_CHANGE = "CONFIGURATION_CHANGE"
    DATA_ACCESS = "DATA_ACCESS"
    PERMISSION_UPDATE = "PERMISSION_UPDATE"

class TicketPriority(discriptors):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    CRITICAL = "CRITICAL"
    BLOCKER = "BLOCKER"
    MAJOR = "MAJOR"
    MINOR = "MINOR"
    URGENT = "URGENT"
    NORMAL = "NORMAL"
    NON_URGENT = "NON_URGENT"

class Permissions(discriptors):
    __READ__ = "READ"
    __WRITE__ = "WRITE"
    __DELETE__ = "DELETE"
    __UPDATE__ = "UPDATE"
    __CREATE__ = "CREATE"
    __ACCESS__ = "ACCESS"
    __MANAGE__ = "MANAGE"
    __EXECUTE__ = "EXECUTE"
    __PRODUCTS__ = "PRODUCTS"
    __SALES__="SALES"
    __OPERATIONS__ = "OPERATIONS"
    __SYSTEM_ADMIN__="SYSTEM_ADMIN"
    __CUSTOMER_SUCCESS_MANAGER__ ="CUSTOMER_SUCCESS_MANAGEMENT"
    __TESTING__="TESTING"
    __SETTINGS__ = "SETTINGS"
    __USERS__ = "USERS"
    __ROLES__ = "ROLES"
    __PERMISSIONS__ = "PERMISSIONS"
    __AUDIT_LOGS__ = "AUDIT_LOGS"
    __INTEGRATION_SETTINGS__ = "INTEGRATION_SETTINGS"
    __EMPLOYEES__ = "EMPLOYEES"
    __FINANCES__ = "FINANCES"
    __CONTRACTS__ = "CONTRACTS"
    __CONTENT__ = "CONTENT"
    __INTEGRATIONS__ = "INTEGRATIONS"
    __VIEW_LOGS__ = "VIEW_LOGS"
    __TICKETS__ = "TICKETS"
    __PROJECTS__ = "PROJECTS"
    __BILLING__ = "BILLING"
    __MARKETING_CAMPAIGNS__ = "MARKETING_CAMPAIGNS"
    __NOTIFICATIONS__ = "NOTIFICATIONS"
    __USER_PROFILE__ = "USER_PROFILE"
    __REPORTS__ = "REPORTS"
    __ORDERS__ = "ORDERS"
    __INVENTORY__ = "INVENTORY"
    __SUPPLY_CHAIN__ = "SUPPLY_CHAIN"
    __COMPLAINTS__ = "COMPLAINTS"
    __APPROVE_EXPENSES__ = "APPROVE_EXPENSES"
    __TRAINING__ = "TRAINING"
    __PARTNERSHIPS__ = "PARTNERSHIPS"
    __LEADERSHIP_TEAM__ = "LEADERSHIP_TEAM"
    __SECURITY__ = "SECURITY"
    __API_KEYS__ = "API_KEYS"
    __COMPLIANCE__ = "COMPLIANCE"
    __BACKUPS__ = "BACKUPS"
    __SLAs__ = "SLAs"
    __CUSTOMER_FEEDBACK__ = "CUSTOMER_FEEDBACK"
    __DOCUMENTS__ = "DOCUMENTS"
    __SUBSCRIPTIONS__ = "SUBSCRIPTIONS"
    __ACCESS_CONTROL__ = "ACCESS_CONTROL"
    __ANALYTICS__ = "ANALYTICS"
    __USER_LOGINS__ = "USER_LOGINS"
    __COMPANY_SETTINGS__ = "COMPANY_SETTINGS"
    __API_LIMITS__ = "API_LIMITS"
    __VIEW_AUDIT_LOGS__ = "VIEW_AUDIT_LOGS"
    __EMPLOYEE_BENEFITS__ = "EMPLOYEE_BENEFITS"
    __RECRUITMENT__ = "RECRUITMENT"
    __APPROVE_HIRING__ = "APPROVE_HIRING"
    __COMPENSATION__ = "COMPENSATION"
    __PERFORMANCE_REVIEWS__ = "PERFORMANCE_REVIEWS"
    __PAYROLL__ = "PAYROLL"
    __TAXES__ = "TAXES"

    
class LanguagePreference(discriptors):
    ENGLISH = "ENGLISH"
    SPANISH = "SPANISH"
    FRENCH = "FRENCH"
    GERMAN = "GERMAN"
    CHINESE = "CHINESE"
    JAPANESE = "JAPANESE"
    HINDI = "HINDI"
    ARABIC = "ARABIC"
    PORTUGUESE = "PORTUGUESE"
    ITALIAN = "ITALIAN"
    RUSSIAN = "RUSSIAN"

class PaymentStatus(discriptors):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"
    CANCELLED = "CANCELLED"
    PROCESSING = "PROCESSING"
    DISPUTED = "DISPUTED"
    EXPIRED = "EXPIRED"
    CHARGEBACK = "CHARGEBACK"
    PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED"

class SubscriptionPlan(discriptors):
    FREE = "FREE"
    BASIC = "BASIC"
    PREMIUM = "PREMIUM"
    ENTERPRISE = "ENTERPRISE"
    CUSTOM = "CUSTOM"
    STARTUP = "STARTUP"
    PROFESSIONAL = "PROFESSIONAL"
    UNLIMITED = "UNLIMITED"
    TRIAL = "TRIAL"
    LIFETIME = "LIFETIME"

class FileType(discriptors):
    DOCUMENT = "DOCUMENT"
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"
    AUDIO = "AUDIO"
    ARCHIVE = "ARCHIVE"
    SPREADSHEET = "SPREADSHEET"
    PRESENTATION = "PRESENTATION"
    DATABASE = "DATABASE"
    CODE = "CODE"
    EXECUTABLE = "EXECUTABLE"

class PrivacyLevel(discriptors):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"
    TOP_SECRET = "TOP_SECRET"
    PERSONAL = "PERSONAL"
    BUSINESS_CRITICAL = "BUSINESS_CRITICAL"
    SENSITIVE = "SENSITIVE"
    UNCLASSIFIED = "UNCLASSIFIED"
    PROPRIETARY = "PROPRIETARY"

class Environment(discriptors):
    DEVELOPMENT = "DEVELOPMENT"
    STAGING = "STAGING"
    TESTING = "TESTING"
    PRODUCTION = "PRODUCTION"
    QA = "QA"
    DEMO = "DEMO"
    SANDBOX = "SANDBOX"

class TaskStatus(discriptors):
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    ON_HOLD = "ON_HOLD"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PENDING_REVIEW = "PENDING_REVIEW"
    ESCALATED = "ESCALATED"

class DocumentType(discriptors):
    IDENTITY_PROOF = "IDENTITY_PROOF"
    ADDRESS_PROOF = "ADDRESS_PROOF"
    BANK_STATEMENT = "BANK_STATEMENT"
    TAX_DOCUMENT = "TAX_DOCUMENT"
    LEGAL_CONTRACT = "LEGAL_CONTRACT"
    INVOICE = "INVOICE"
    RECEIPT = "RECEIPT"
    PROPOSAL = "PROPOSAL"
    REPORT = "REPORT"
    OTHER = "OTHER"

class DeviceType(discriptors):
    MOBILE = "MOBILE"
    DESKTOP = "DESKTOP"
    TABLET = "TABLET"
    SMART_WATCH = "SMART_WATCH"
    SMART_TV = "SMART_TV"
    CONSOLE = "CONSOLE"
    IoT_DEVICE = "IoT_DEVICE"
    WEARABLE = "WEARABLE"
    EMBEDDED_SYSTEM = "EMBEDDED_SYSTEM"
    OTHER = "OTHER"

class WorkflowStage(discriptors):
    INITIATION = "INITIATION"
    PLANNING = "PLANNING"
    EXECUTION = "EXECUTION"
    MONITORING = "MONITORING"
    CLOSURE = "CLOSURE"
    DEPLOYMENT = "DEPLOYMENT"
    VALIDATION = "VALIDATION"
    MAINTENANCE = "MAINTENANCE"
    ARCHIVING = "ARCHIVING"
    TERMINATION = "TERMINATION"

class APIRequestMethod(discriptors):
    GET = "GET"
    POST = "POST"
    PUT = "PUT"
    DELETE = "DELETE"
    PATCH = "PATCH"
    OPTIONS = "OPTIONS"
    HEAD = "HEAD"
    CONNECT = "CONNECT"
    TRACE = "TRACE"

class FeatureFlag(discriptors):
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
    BETA = "BETA"
    DEPRECATED = "DEPRECATED"
    ALPHA = "ALPHA"
    ROLLED_BACK = "ROLLED_BACK"
    EXPERIMENTAL = "EXPERIMENTAL"
    GA = "GA"
    LEGACY = "LEGACY"
    UPCOMING = "UPCOMING"

class IntegrationType(discriptors):
    PAYMENT_GATEWAY = "PAYMENT_GATEWAY"
    CRM = "CRM"
    EMAIL = "EMAIL"
    SMS = "SMS"
    SOCIAL_MEDIA = "SOCIAL_MEDIA"
    CLOUD_STORAGE = "CLOUD_STORAGE"
    WEBHOOK = "WEBHOOK"
    DATABASE = "DATABASE"
    API = "API"
    THIRD_PARTY_APP = "THIRD_PARTY_APP"

class ProjectCategory(discriptors):
    FINANCE = "FINANCE"
    HEALTHCARE = "HEALTHCARE"
    EDUCATION = "EDUCATION"
    RETAIL = "RETAIL"
    ECOMMERCE = "ECOMMERCE"
    LOGISTICS = "LOGISTICS"
    ENTERTAINMENT = "ENTERTAINMENT"
    TECHNOLOGY = "TECHNOLOGY"
    AUTOMOTIVE = "AUTOMOTIVE"
    REAL_ESTATE = "REAL_ESTATE"


class SubscriptionTier(discriptors):
    FREE = "FREE"
    STARTER = "STARTER"
    GROWTH = "GROWTH"
    BUSINESS = "BUSINESS"
    ENTERPRISE = "ENTERPRISE"
    CUSTOM = "CUSTOM"
    PAY_AS_YOU_GO = "PAY_AS_YOU_GO"
    UNLIMITED = "UNLIMITED"
    NON_PROFIT = "NON_PROFIT"
    EDUCATIONAL = "EDUCATIONAL"
