from enum import Enum as discriptors
class __NULLABLES__(discriptors):
    __NULLABLES__ = ['NULLABLE', 'NOT NULLABLE']
    EMPTY_STATE = ""


Criticals = {
    "__TRACE__": {
        "value": "TRACE",
    },
    "__DEBUG__": {
        "value": "DEBUG",
    },
    "__INFO__": {
        "value": "INFO",
    },
    "__WARNING__": {
        "value": "WARNING",
    },
    "__ERROR__": {
        "value": "ERROR",
    },
    "__CRITICAL__": {
        "value": "CRITICAL",
    },
    "__ALERT__": {
        "value": "ALERT",
    },
    "__EMERGENCY__": {
        "value": "EMERGENCY",
    }
}



class Role(discriptors):
    SUPER_ADMIN = "SUPER_ADMIN"
    AGENCY_OWNER = "AGENCY_OWNER"
    AGENCY_ADMIN = "AGENCY_ADMIN"
    SUBACCOUNT_USER = "SUBACCOUNT_USER"
    SUBACCOUNT_GUEST = "SUBACCOUNT_GUEST"
    CUSTOMER = "CUSTOMER"
    SUPPORT = "SUPPORT"
    AUDITOR = "AUDITOR"
    TEAM_LEAD = "TEAM_LEAD"
    PRODUCT_MANAGER = "PRODUCT_MANAGER"
    SALES_REPRESENTATIVE = "SALES_REPRESENTATIVE"
    DEVELOPER = "DEVELOPER"
    MARKETING_SPECIALIST = "MARKETING_SPECIALIST"
    DATA_ANALYST = "DATA_ANALYST"

class InvitationStatus(discriptors):
    ACCEPTED = "ACCEPTED"
    REVOKED = "REVOKED"
    PENDING = "PENDING"
    EXPIRED = "EXPIRED"
    DECLINED = "DECLINED"
    REISSUED = "REISSUED"
    SUSPENDED = "SUSPENDED"
    INACTIVE = "INACTIVE"
    COMPLETED = "COMPLETED"
    INVALID = "INVALID"

class ProjectStatus(discriptors):
    ACTIVE = "Active"
    COMPLETED = "Completed"
    ON_HOLD = "On Hold"
    CANCELLED = "Cancelled"

class AccountStatus(discriptors):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    LOCKED = "LOCKED"
    DELETED = "DELETED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    ARCHIVED = "ARCHIVED"
    DISABLED = "DISABLED"
    INACTIVE = "INACTIVE"
    UNVERIFIED = "UNVERIFIED"
    TEMPORARY = "TEMPORARY"

class AuthProvider(discriptors):
    LOCAL = "LOCAL"
    GOOGLE = "GOOGLE"
    FACEBOOK = "FACEBOOK"
    TWITTER = "TWITTER"
    GITHUB = "GITHUB"
    APPLE = "APPLE"
    LINKEDIN = "LINKEDIN"
    MICROSOFT = "MICROSOFT"
    AMAZON = "AMAZON"
    SLACK = "SLACK"
    INSTAGRAM = "INSTAGRAM"
    ZOOM = "ZOOM"

class NotificationType(discriptors):
    EMAIL = "EMAIL"
    SMS = "SMS"
    PUSH = "PUSH"
    IN_APP = "IN_APP"
    WEBHOOK = "WEBHOOK"
    WHATSAPP = "WHATSAPP"
    TELEGRAM = "TELEGRAM"
    SLACK = "SLACK"
    BROWSER = "BROWSER"
    DESKTOP_ALERT = "DESKTOP_ALERT"
    NEWSLETTER = "NEWSLETTER"

class AuditAction(discriptors):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    EXPORT = "EXPORT"
    IMPORT = "IMPORT"
    ACCESS_DENIED = "ACCESS_DENIED"
    PASSWORD_RESET = "PASSWORD_RESET"
    CONFIGURATION_CHANGE = "CONFIGURATION_CHANGE"
    DATA_ACCESS = "DATA_ACCESS"
    PERMISSION_UPDATE = "PERMISSION_UPDATE"

class TicketPriority(discriptors):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    CRITICAL = "CRITICAL"
    BLOCKER = "BLOCKER"
    MAJOR = "MAJOR"
    MINOR = "MINOR"
    URGENT = "URGENT"
    NORMAL = "NORMAL"
    NON_URGENT = "NON_URGENT"

class Permissions(discriptors):
    __READ__ = "READ"
    __WRITE__ = "WRITE"
    __DELETE__ = "DELETE"
    __UPDATE__ = "UPDATE"
    __CREATE__ = "CREATE"
    __ACCESS__ = "ACCESS"
    __MANAGE__ = "MANAGE"
    __EXECUTE__ = "EXECUTE"
    MANAGE_SETTINGS = "MANAGE_SETTINGS"
    MANAGE_USERS = "MANAGE_USERS"
    MANAGE_ROLES = "MANAGE_ROLES"
    MANAGE_PERMISSIONS = "MANAGE_PERMISSIONS"
    MANAGE_AUDIT_LOGS = "MANAGE_AUDIT_LOGS"
    MANAGE_INTEGRATION_SETTINGS = "MANAGE_INTEGRATION_SETTINGS"
    
class LanguagePreference(discriptors):
    ENGLISH = "ENGLISH"
    SPANISH = "SPANISH"
    FRENCH = "FRENCH"
    GERMAN = "GERMAN"
    CHINESE = "CHINESE"
    JAPANESE = "JAPANESE"
    HINDI = "HINDI"
    ARABIC = "ARABIC"
    PORTUGUESE = "PORTUGUESE"
    ITALIAN = "ITALIAN"
    RUSSIAN = "RUSSIAN"

class PaymentStatus(discriptors):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"
    CANCELLED = "CANCELLED"
    PROCESSING = "PROCESSING"
    DISPUTED = "DISPUTED"
    EXPIRED = "EXPIRED"
    CHARGEBACK = "CHARGEBACK"
    PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED"

class SubscriptionPlan(discriptors):
    FREE = "FREE"
    BASIC = "BASIC"
    PREMIUM = "PREMIUM"
    ENTERPRISE = "ENTERPRISE"
    CUSTOM = "CUSTOM"
    STARTUP = "STARTUP"
    PROFESSIONAL = "PROFESSIONAL"
    UNLIMITED = "UNLIMITED"
    TRIAL = "TRIAL"
    LIFETIME = "LIFETIME"

class FileType(discriptors):
    DOCUMENT = "DOCUMENT"
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"
    AUDIO = "AUDIO"
    ARCHIVE = "ARCHIVE"
    SPREADSHEET = "SPREADSHEET"
    PRESENTATION = "PRESENTATION"
    DATABASE = "DATABASE"
    CODE = "CODE"
    EXECUTABLE = "EXECUTABLE"

class PrivacyLevel(discriptors):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"
    TOP_SECRET = "TOP_SECRET"
    PERSONAL = "PERSONAL"
    BUSINESS_CRITICAL = "BUSINESS_CRITICAL"
    SENSITIVE = "SENSITIVE"
    UNCLASSIFIED = "UNCLASSIFIED"
    PROPRIETARY = "PROPRIETARY"

class Environment(discriptors):
    DEVELOPMENT = "DEVELOPMENT"
    STAGING = "STAGING"
    TESTING = "TESTING"
    PRODUCTION = "PRODUCTION"
    QA = "QA"
    DEMO = "DEMO"
    SANDBOX = "SANDBOX"

class TaskStatus(discriptors):
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    ON_HOLD = "ON_HOLD"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PENDING_REVIEW = "PENDING_REVIEW"
    ESCALATED = "ESCALATED"

class DocumentType(discriptors):
    IDENTITY_PROOF = "IDENTITY_PROOF"
    ADDRESS_PROOF = "ADDRESS_PROOF"
    BANK_STATEMENT = "BANK_STATEMENT"
    TAX_DOCUMENT = "TAX_DOCUMENT"
    LEGAL_CONTRACT = "LEGAL_CONTRACT"
    INVOICE = "INVOICE"
    RECEIPT = "RECEIPT"
    PROPOSAL = "PROPOSAL"
    REPORT = "REPORT"
    OTHER = "OTHER"

class DeviceType(discriptors):
    MOBILE = "MOBILE"
    DESKTOP = "DESKTOP"
    TABLET = "TABLET"
    SMART_WATCH = "SMART_WATCH"
    SMART_TV = "SMART_TV"
    CONSOLE = "CONSOLE"
    IoT_DEVICE = "IoT_DEVICE"
    WEARABLE = "WEARABLE"
    EMBEDDED_SYSTEM = "EMBEDDED_SYSTEM"
    OTHER = "OTHER"

class WorkflowStage(discriptors):
    INITIATION = "INITIATION"
    PLANNING = "PLANNING"
    EXECUTION = "EXECUTION"
    MONITORING = "MONITORING"
    CLOSURE = "CLOSURE"
    DEPLOYMENT = "DEPLOYMENT"
    VALIDATION = "VALIDATION"
    MAINTENANCE = "MAINTENANCE"
    ARCHIVING = "ARCHIVING"
    TERMINATION = "TERMINATION"

class APIRequestMethod(discriptors):
    GET = "GET"
    POST = "POST"
    PUT = "PUT"
    DELETE = "DELETE"
    PATCH = "PATCH"
    OPTIONS = "OPTIONS"
    HEAD = "HEAD"
    CONNECT = "CONNECT"
    TRACE = "TRACE"

class FeatureFlag(discriptors):
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
    BETA = "BETA"
    DEPRECATED = "DEPRECATED"
    ALPHA = "ALPHA"
    ROLLED_BACK = "ROLLED_BACK"
    EXPERIMENTAL = "EXPERIMENTAL"
    GA = "GA"
    LEGACY = "LEGACY"
    UPCOMING = "UPCOMING"

class IntegrationType(discriptors):
    PAYMENT_GATEWAY = "PAYMENT_GATEWAY"
    CRM = "CRM"
    EMAIL = "EMAIL"
    SMS = "SMS"
    SOCIAL_MEDIA = "SOCIAL_MEDIA"
    CLOUD_STORAGE = "CLOUD_STORAGE"
    WEBHOOK = "WEBHOOK"
    DATABASE = "DATABASE"
    API = "API"
    THIRD_PARTY_APP = "THIRD_PARTY_APP"

class ProjectCategory(discriptors):
    FINANCE = "FINANCE"
    HEALTHCARE = "HEALTHCARE"
    EDUCATION = "EDUCATION"
    RETAIL = "RETAIL"
    ECOMMERCE = "ECOMMERCE"
    LOGISTICS = "LOGISTICS"
    ENTERTAINMENT = "ENTERTAINMENT"
    TECHNOLOGY = "TECHNOLOGY"
    AUTOMOTIVE = "AUTOMOTIVE"
    REAL_ESTATE = "REAL_ESTATE"


class SubscriptionTier(discriptors):
    FREE = "FREE"
    STARTER = "STARTER"
    GROWTH = "GROWTH"
    BUSINESS = "BUSINESS"
    ENTERPRISE = "ENTERPRISE"
    CUSTOM = "CUSTOM"
    PAY_AS_YOU_GO = "PAY_AS_YOU_GO"
    UNLIMITED = "UNLIMITED"
    NON_PROFIT = "NON_PROFIT"
    EDUCATIONAL = "EDUCATIONAL"
